name: rtg
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.7
  - sqlite>=3.25
  - pip>=19.1
  - pip:
    - ruamel.yaml>=0.15.97
    - sacrebleu==1.3.6
    - scipy==1.2.1
    - sentencepiece==0.1.82
    - tensorboardx==1.4
    - torch==1.1.0
    - torchvision>=0.2.2
    - tqdm==4.25.0
    - typing==3.6.6
    - mosestokenizer>=1.0.0
