name: rtg
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.7
  - sqlite>=3.25
  - pip>=19.1
  - pytorch=1.2.0
  - torchvision=0.4.0
  - cudatoolkit=9.2
  - pip:
    - ruamel.yaml>=0.15.97
    - sacrebleu==1.3.6
    - scipy==1.2.1
    - sentencepiece==0.1.82
    - tensorboard==2.0.1
    - future==0.18.2
    - tqdm==4.25.0
    - typing==3.6.6
    - mosestokenizer>=1.0.0
