model_args:
  dec_layers: 2
  emb_size: 300
  enc_layers: 2
  hid_size: 300
  rnn_type: lstm
  src_vocab: 8000
  tgt_vocab: 8000
model_type: rnn
optim:
  args:
    lr: 0.001
  name: ADAM
pieces: unigram
prep:
  mono_src: []
  mono_tgt: []
  src_len: 100
  text_pieces: false
  tgt_len: 100
  train_src: data/train.src
  train_tgt: data/train.tgt
  truncate: true
  valid_src: data/valid.src
  valid_tgt: data/valid.tgt
  shared_vocab: true
src_lang: FRA
tgt_lang: ENG
updated_at: '2018-07-25T15:50:52.578881'
vocab_size: 8000
