model_args:
  dropout: 0.1
  ff_size: 512
  hid_size: 512
  n_heads: 4
  n_layers: 4
  src_vocab: 8000
  tgt_vocab: 8000
model_type: t2t
optim:
  args:
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    lr: 0.001
  name: ADAM
pieces: unigram
prep:
  mono_src: []
  mono_tgt: []
  src_len: 100
  tgt_len: 100
  train_src: data/train.src
  train_tgt: data/train.tgt
  truncate: true
  valid_src: data/valid.src
  valid_tgt: data/valid.tgt
  shared_vocab: true
src_lang: FRA
test_src: null
test_tgt: null
tgt_lang: ENG
updated_at: '2018-07-25T15:53:18.379150'
vocab_size: 8000
